name: DevContainer CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.cache/devcontainers
          key: devcontainer-${{ hashFiles('.devcontainer/Dockerfile', '.devcontainer/devcontainer.json') }}
          restore-keys: |
            devcontainer-

      - name: Run tests in DevContainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            python3 -m venv tests/.venv
            source tests/.venv/bin/activate
            pip install --upgrade pip
            pip install -r tests/requirements.txt
            pytest -v tests/
